# tasks file
---
- name: create (download) directory
  ansible.builtin.file:
    path: "{{ phpmemcachedadmin_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - phpmemcachedadmin-download-directory

- name: download
  ansible.builtin.get_url:
    url: "{{ phpmemcachedadmin_download_url }}"
    dest: "{{ phpmemcachedadmin_download_path }}/{{ phpmemcachedadmin_download_url | basename }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - phpmemcachedadmin-download-get-url
