# tasks file for phpmemcachedadmin
---
- name: create (download) directory
  file:
    path: "{{ phpmemcachedadmin_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, phpmemcachedadmin, phpmemcachedadmin-download, phpmemcachedadmin-download-directory]

- name: download
  get_url:
    url: "{{ phpmemcachedadmin_download_url }}"
    dest: "{{ phpmemcachedadmin_download_path }}/{{ phpmemcachedadmin_download_url | basename }}"
    owner: root
    group: root
    mode: 0644
  tags: [configuration, phpmemcachedadmin, phpmemcachedadmin-download, phpmemcachedadmin-download-get-url]
