# tasks file
---
- name: download
  ansible.builtin.import_tasks: download.yml
  tags:
    - configuration
    - phpmemcachedadmin
    - phpmemcachedadmin-download

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - phpmemcachedadmin
    - phpmemcachedadmin-install

- name: remove
  ansible.builtin.import_tasks: remove.yml
  tags:
    - configuration
    - phpmemcachedadmin
    - phpmemcachedadmin-remove
