# tasks file
---
- name: remove
  ansible.builtin.file:
    path: "{{ item.dest }}/phpMemcachedAdmin-{{ phpmemcachedadmin_version }}"
    state: absent
  with_items: "{{ phpmemcachedadmin_install_dirs }}"
  when: item.state is defined and item.state == 'absent'
